"""Robustness Certification Module.

Generates professional certificates for validated indicators.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any

from monte_neo.utils.logger import get_logger

logger = get_logger(__name__)

class RobustnessCertifier:
    """Generates a 'World Top 1' Robustness Certificate for indicators."""

    def __init__(self, output_dir: str = "exports/certificates"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_certificate(self, indicator_name: str, validation_status: dict[str, Any]) -> str:
        """
        Generates a markdown certificate summarizing robustness metrics.
        
        Returns:
            Path to the certificate file.
        """
        score = validation_status.get("robustness_score", 0.0)
        is_ready = validation_status.get("is_production_ready", False)
        
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        cert_id = f"CERT-{int(datetime.now().timestamp())}"
        
        content = f"""# 🏆 Monte-Neo Robustness Certificate
**ID:** {cert_id}
**Date:** {timestamp}
**Indicator:** {indicator_name}

---

## 📊 Robustness Summary
- **Overall Score:** {score}/100
- **Production Status:** {"✅ READY" if is_ready else "❌ REJECTED"}
- **Walk-Forward Efficiency (WFE):** {validation_status.get('wfe', 'N/A')}
- **Monte Carlo Robustness:** {validation_status.get('mc_robustness', 'N/A')}
- **Stress Test Score:** {validation_status.get('stress_test_score', 'N/A')}

---

## 🛡️ Validation Checks
- **Non-Repainting Test:** {"✅ PASSED" if "REPAINTS" not in str(validation_status.get('recommendation')) else "❌ FAILED"}
- **PBO (Probability of Overfitting):** {validation_status.get('pbo', 'N/A')}
- **Consistency Score:** {validation_status.get('consistency', 'N/A')}

---

## 📜 Recommendation
{validation_status.get('recommendation', 'No recommendation available.')}

---
*Generated by Monte-Neo v0.0.6 - The World's #1 Indicator Framework*
"""
        
        cert_path = os.path.join(self.output_dir, f"certificate_{indicator_name}_{cert_id}.md")
        with open(cert_path, 'w') as f:
            f.write(content)
            
        logger.info(f"Certificate generated at {cert_path}")
        return cert_path
