"""Mechanisms of the hypothesis zoo: leaks (known to read the future) and honest twins (causal look-alikes).

Each row is (id, group, expression over ``df``, rule[, setup lines]). The label comes from the list a row is in;
``test_zoo_labels.py`` checks every label with an oracle that does not use the verifier.
"""

from __future__ import annotations

C, H, L, O, V = 'df["close"]', 'df["high"]', 'df["low"]', 'df["open"]', 'df["volume"]'
TS = 'pd.to_datetime(df["timestamp"])'
DAY = f'{TS}.dt.date'
CL = 'df["close"].to_numpy()'


def _series(arr: str) -> str:
    return f"pd.Series({arr}, index=df.index)"


# ---- leaks -------------------------------------------------------------------------------------------------
LEAKS: list[tuple] = [
    # pandas windows and shifts
    ("pw_shift_close_1", "windows", f"{C}.shift(-1)", "R1"),
    ("pw_shift_close_5", "windows", f"{C}.shift(-5)", "R1"),
    ("pw_shift_close_20", "windows", f"{C}.shift(-20)", "R1"),
    ("pw_shift_high_3", "windows", f"{H}.shift(-3)", "R1"),
    ("pw_shift_low_3", "windows", f"{L}.shift(-3)", "R1"),
    ("pw_shift_open_2", "windows", f"{O}.shift(-2)", "R1"),
    ("pw_shift_volume", "windows", f"{V}.shift(-1)", "R3"),
    ("pw_center_mean", "windows", f"{C}.rolling(20, center=True, min_periods=1).mean()", "R1"),
    ("pw_center_median", "windows", f"{C}.rolling(15, center=True, min_periods=1).median()", "R1"),
    ("pw_center_max", "windows", f"{C}.rolling(15, center=True, min_periods=1).max()", "R1"),
    ("pw_center_min", "windows", f"{C}.rolling(15, center=True, min_periods=1).min()", "R1"),
    ("pw_center_std", "windows", f"{C}.rolling(9, center=True, min_periods=2).std()", "R3"),
    ("pw_center_high_max", "windows", f"{H}.rolling(11, center=True, min_periods=1).max()", "R3"),
    ("pw_reversed_mean", "windows", f"{C}[::-1].rolling(10, min_periods=1).mean()[::-1]", "R1"),
    ("pw_reversed_ewm", "windows", f"{C}[::-1].ewm(span=10).mean()[::-1]", "R1"),
    ("pw_reversed_cummax", "windows", f"{C}[::-1].cummax()[::-1]", "R1"),
    ("pw_reversed_return_sum", "windows", f'{C}.pct_change().fillna(0)[::-1].cumsum()[::-1]', "R5"),
    ("pw_forward_indexer", "windows", f"{C}.rolling(pd.api.indexers.FixedForwardWindowIndexer(window_size=10), min_periods=1).mean()", "R1"),
    ("pw_pct_change_negative", "windows", f"{C}.pct_change(-5)", "R2"),
    ("pw_diff_negative", "windows", f"{C}.diff(-3)", "R2"),
    ("pw_np_roll_negative", "windows", _series(f"np.roll({CL}, -4)"), "R1"),
    ("pw_corr_with_future", "windows", f"{C}.rolling(20).corr({C}.shift(-5))", "R3"),
    ("pw_future_return_sum", "windows", f"{C}.pct_change().shift(-1).rolling(5, min_periods=1).sum()", "R5"),
    ("pw_apply_then_shift", "windows", f"{C}.rolling(5, min_periods=1).apply(lambda w: w[-1], raw=True).shift(-2)", "R1"),
    # time, resampling and alignment
    ("ti_daily_last", "time", f"{C}.groupby({DAY}).transform('last')", "R1"),
    ("ti_daily_max", "time", f"{C}.groupby({DAY}).transform('max')", "R1"),
    ("ti_daily_min", "time", f"{C}.groupby({DAY}).transform('min')", "R1"),
    ("ti_daily_mean", "time", f"{C}.groupby({DAY}).transform('mean')", "R1"),
    ("ti_daily_high", "time", f"{H}.groupby({DAY}).transform('max')", "R3"),
    ("ti_four_hour_last", "time", f"{C}.groupby({TS}.dt.floor('4h')).transform('last')", "R1"),
    ("ti_weekly_last", "time", f"{C}.groupby({TS}.dt.to_period('W')).transform('last')", "R1"),
    ("ti_bars_left_in_day", "time", f"{C}.groupby({DAY}).cumcount(ascending=False)", "R9"),
    ("ti_bfill_sparse", "time", f"{C}.where(np.arange(len(df)) % 5 == 0).bfill()", "R1"),
    ("ti_interpolate_sparse", "time", f"{C}.where(np.arange(len(df)) % 7 == 0).interpolate(limit_direction='both')", "R1"),
    ("ti_resample_last_ffill", "time", _series(f"{C}.set_axis({TS}).resample('1D').last().reindex({TS}, method='ffill').to_numpy()"), "R1"),
    ("ti_resample_max_ffill", "time", _series(f"{C}.set_axis({TS}).resample('1D').max().reindex({TS}, method='ffill').to_numpy()"), "R1"),
    ("ti_reindex_bfill", "time", _series(f"{C}.set_axis({TS}).iloc[::6].reindex({TS}, method='bfill').to_numpy()"), "R1"),
    ("ti_reindex_nearest", "time", _series(f"{C}.set_axis({TS}).iloc[::6].reindex({TS}, method='nearest').to_numpy()"), "R1"),
    # ranks and whole-sample statistics
    ("rs_rank_pct", "wholesample", f"{C}.rank(pct=True)", "R8"),
    ("rs_qcut", "wholesample", f"pd.qcut({C}, 5, labels=False, duplicates='drop')", "R9"),
    ("rs_cut_bins", "wholesample", f"pd.cut({C}, 5, labels=False)", "R9"),
    ("rs_zscore", "wholesample", f"({C} - {C}.mean()) / {C}.std()", "R2"),
    ("rs_minmax", "wholesample", f"({C} - {C}.min()) / ({C}.max() - {C}.min())", "R8"),
    ("rs_quantile", "wholesample", f"{C} - {C}.quantile(0.5)", "R2"),
    ("rs_median", "wholesample", f"{C} - {C}.median()", "R2"),
    ("rs_describe", "wholesample", f"{C} - {C}.describe()['75%']", "R2"),
    ("rs_nlargest", "wholesample", f"{C} - {C}.nlargest(10).iloc[-1]", "R2"),
    ("rs_idxmax", "wholesample", _series(f"np.arange(len(df)) - {C}.idxmax()"), "R2"),
    ("rs_argmax_np", "wholesample", _series(f"np.arange(len(df)) - np.argmax({CL})"), "R2"),
    ("rs_np_mean", "wholesample", f"{C} - np.mean({CL})", "R2"),
    ("rs_np_percentile", "wholesample", f"{C} - np.percentile({CL}, 60)", "R2"),
    ("rs_np_sorted_median", "wholesample", f"{C} - np.sort({CL})[len(df) // 2]", "R2"),
    ("rs_np_argsort_rank", "wholesample", _series(f"np.argsort(np.argsort({CL})) / len(df)"), "R8"),
    ("rs_np_searchsorted", "wholesample", _series(f"np.searchsorted(np.sort({CL}), {CL}) / len(df)"), "R8"),
    ("rs_np_digitize", "wholesample", _series(f"np.digitize({CL}, np.quantile({CL}, [.2, .4, .6, .8]))"), "R9"),
    ("rs_block_mean", "wholesample", f"{C}.groupby(df.index // 100).transform('mean')", "R1"),
    ("rs_last_row", "wholesample", f"{C} - {C}.iloc[-1]", "R2"),
    ("rs_tail_mean", "wholesample", f"{C} - {C}.tail(100).mean()", "R2"),
    ("rs_scaled_max", "wholesample", f"{C} - 0.99 * {C}.max()", "R2"),
    ("rs_mode_level", "wholesample", f"{C}.round(-1) - {C}.round(-1).mode()[0]", "R2"),
    ("rs_hindsight_winner", "wholesample", f"{C}*0 + np.sign({C}.iloc[-1] - {C}.iloc[0])", "R5"),
    # numpy and scipy over whole arrays
    ("ns_polyfit", "arrays", _series(f"np.polyval(np.polyfit(np.arange(len(df)), {CL}, 2), np.arange(len(df)))"), "R1"),
    ("ns_gradient", "arrays", _series(f"np.gradient({CL})"), "R5"),
    ("ns_convolve_same", "arrays", _series(f"np.convolve({CL}, np.ones(9) / 9, mode='same')"), "R1"),
    ("ns_fft_lowpass", "arrays", _series(f"np.fft.irfft(np.where(np.arange(len(df) // 2 + 1) < 30, np.fft.rfft({CL}), 0), n=len(df))"), "R1"),
    ("ns_interp_sparse", "arrays", _series(f"np.interp(np.arange(len(df)), np.arange(0, len(df), 10), {CL}[::10])"), "R1"),
    ("ns_diff_append", "arrays", _series(f"np.diff({CL}, append={CL}[-1])"), "R5"),
    ("ns_cumsum_reversed", "arrays", _series(f"np.cumsum(np.diff({CL}, prepend={CL}[0])[::-1])[::-1]"), "R5"),
    ("sc_filtfilt", "arrays", _series(f"scipy.signal.filtfilt([0.2] * 5, [1], {CL})"), "R1"),
    ("sc_savgol", "arrays", _series(f"scipy.signal.savgol_filter({CL}, 21, 2)"), "R1"),
    ("sc_savgol_derivative", "arrays", _series(f"scipy.signal.savgol_filter({CL}, 11, 2, deriv=1)"), "R5"),
    ("sc_gaussian_filter", "arrays", _series(f"scipy.ndimage.gaussian_filter1d({CL}, 3)"), "R1"),
    ("sc_uniform_filter", "arrays", _series(f"scipy.ndimage.uniform_filter1d({CL}, 9)"), "R1"),
    ("sc_median_filter", "arrays", _series(f"scipy.signal.medfilt({CL}, 9)"), "R1"),
    ("sc_detrend", "arrays", _series(f"scipy.signal.detrend({CL})"), "R2"),
    ("sc_hilbert", "arrays", _series(f"np.imag(scipy.signal.hilbert({CL} - {CL}.mean()))"), "R5"),
    ("sc_interp1d_cubic", "arrays", _series(f"scipy.interpolate.interp1d(np.arange(0, len(df), 10), {CL}[::10], kind='cubic', fill_value='extrapolate')(np.arange(len(df)))"), "R1"),
    ("sc_spline", "arrays", _series(f"scipy.interpolate.UnivariateSpline(np.arange(len(df)), {CL}, s=len(df))(np.arange(len(df)))"), "R1"),
    ("sc_zscore", "arrays", _series(f"scipy.stats.zscore({CL})"), "R2"),
    ("sc_rankdata", "arrays", _series(f"scipy.stats.rankdata({CL}) / len(df)"), "R8"),
    ("sc_lfilter_reversed", "arrays", _series(f"scipy.signal.lfilter([0.2] * 5, [1], {CL}[::-1])[::-1]"), "R1"),
    # fits and encodings on the whole sample
    ("ml_pca_first_component", "fits", _series('(lambda m: (m - m.mean(0)) @ np.linalg.eigh(np.cov(m.T))[1][:, -1])(df[["open", "high", "low", "close"]].to_numpy())'), "R5"),
    ("ml_lstsq_in_sample", "fits", _series('(lambda f, y: np.c_[np.ones(len(f)), f] @ np.linalg.lstsq(np.c_[np.ones(len(f)), f], y, rcond=None)[0])(df["close"].pct_change().fillna(0).to_numpy(), df["close"].pct_change().shift(-1).fillna(0).to_numpy())'), "R5"),
    ("ml_target_encoding", "fits", f'{C}.pct_change().shift(-1).groupby(pd.qcut({C}.pct_change().fillna(0), 5, labels=False, duplicates="drop")).transform("mean")', "R5"),
    ("ml_expanding_future_label", "fits", f"{C}.pct_change().shift(-1).expanding().mean()", "R3"),
    ("ml_season_hour_profile", "fits", f"{C}.groupby({TS}.dt.hour).transform('mean')", "R1"),
    ("ml_weekday_return_profile", "fits", f"{C}.pct_change().groupby({TS}.dt.dayofweek).transform('mean')", "R5"),
    # indicators and patterns
    ("ip_pivot_high_confirmed", "indicators", f"({H} == {H}.rolling(5, center=True).max()).astype(float)", "R10"),
    ("ip_fractal_low", "indicators", f"({L} == {L}.rolling(5, center=True).min()).astype(float)", "R10"),
    ("ip_ichimoku_chikou", "indicators", f"{C}.shift(-26)", "R1"),
    ("ip_daily_vwap_full", "indicators", f"({C} * {V}).groupby({DAY}).transform('sum') / {V}.groupby({DAY}).transform('sum')", "R1"),
    ("ip_next_window_high", "indicators", f"{H}.rolling(10).max().shift(-10)", "R1"),
    ("ip_next_window_low", "indicators", f"{L}.rolling(10).min().shift(-10)", "R1"),
    # labels and targets
    ("lb_forward_return_5", "labels", f"{C}.pct_change(5).shift(-5)", "R5"),
    ("lb_forward_direction_10", "labels", f"np.sign({C}.shift(-10) - {C})", "R5"),
    ("lb_time_to_max", "labels", f"{C}[::-1].rolling(20, min_periods=1).apply(lambda w: np.argmax(w), raw=True)[::-1]", "R11"),
    ("lb_vol_scaled_future", "labels", f"{C}.pct_change().shift(-1) / {C}.pct_change().rolling(20).std()", "R5"),
    ("lb_barrier_hit", "labels", f"({H}[::-1].rolling(10, min_periods=1).max()[::-1] > {C} * 1.001).astype(float)", "R10"),
    ("lb_next_high", "labels", f"{H}.shift(-1) - {C}", "R5"),
    # point-in-time errors
    ("ev_restated_series", "pit", f"{C}.rolling(63, min_periods=1).mean().shift(-5)", "R1"),
    ("ev_split_factor_by_length", "pit", f"{C} * (1 + (np.arange(len(df)) < len(df) // 2) * 0.05)", "R3"),
]

# ---- honest twins ----------------------------------------------------------------------------------------
HONEST: list[tuple] = [
    ("hw_rolling_mean", "windows", f"{C}.rolling(20).mean()", "R1"),
    ("hw_rolling_median", "windows", f"{C}.rolling(15).median()", "R1"),
    ("hw_rolling_max", "windows", f"{C}.rolling(15).max()", "R1"),
    ("hw_rolling_min", "windows", f"{C}.rolling(15).min()", "R1"),
    ("hw_rolling_std", "windows", f"{C}.rolling(9).std()", "R3"),
    ("hw_rolling_quantile", "windows", f"{C}.rolling(30).quantile(0.8)", "R1"),
    ("hw_rolling_rank", "windows", f"{C}.rolling(30).rank(pct=True)", "R8"),
    ("hw_rolling_skew", "windows", f"{C}.pct_change().rolling(40).skew()", "R2"),
    ("hw_rolling_corr_lag", "windows", f"{C}.rolling(20).corr({C}.shift(1))", "R3"),
    ("hw_ewm_mean", "windows", f"{C}.ewm(span=10).mean()", "R1"),
    ("hw_ewm_std", "windows", f"{C}.pct_change().ewm(span=20).std()", "R3"),
    ("hw_expanding_mean", "windows", f"{C}.expanding().mean()", "R1"),
    ("hw_expanding_median", "windows", f"{C}.expanding().median()", "R1"),
    ("hw_expanding_max", "windows", f"{C}.expanding().max()", "R1"),
    ("hw_expanding_std", "windows", f"{C}.pct_change().expanding().std()", "R3"),
    ("hw_expanding_zscore", "windows", f"({C} - {C}.expanding().mean()) / {C}.expanding().std()", "R2"),
    ("hw_rolling_zscore", "windows", f"({C} - {C}.rolling(30).mean()) / {C}.rolling(30).std()", "R2"),
    ("hw_shift_plus_1", "windows", f"{C}.shift(1)", "R1"),
    ("hw_shift_plus_5", "windows", f"{C}.shift(5)", "R1"),
    ("hw_shift_plus_20", "windows", f"{C}.shift(20)", "R1"),
    ("hw_diff_3", "windows", f"{C}.diff(3)", "R5"),
    ("hw_pct_change_5", "windows", f"{C}.pct_change(5)", "R5"),
    ("hw_cummax_drawdown", "windows", f"{C} / {C}.cummax() - 1", "R10"),
    ("hw_cumsum_returns", "windows", f"{C}.pct_change().fillna(0).cumsum()", "R3"),
    ("hw_apply_last", "windows", f"{C}.rolling(5, min_periods=1).apply(lambda w: w[-1], raw=True)", "R1"),
    ("hw_bollinger_z", "windows", f"({C} - {C}.rolling(20).mean()) / (2 * {C}.rolling(20).std())", "R2"),
    ("hw_macd", "windows", f"{C}.ewm(span=12).mean() - {C}.ewm(span=26).mean()", "R5"),
    ("hw_rsi", "windows", f"{C}.diff().clip(lower=0).rolling(14).mean() / ({C}.diff().abs().rolling(14).mean() + 1e-12) - 0.5", "R5"),
    ("hw_atr_breakout", "windows", f"{C} - ({H} - {L}).rolling(14).mean()", "R3"),
    ("hw_stochastic", "windows", f"({C} - {L}.rolling(14).min()) / ({H}.rolling(14).max() - {L}.rolling(14).min() + 1e-12) - 0.5", "R5"),
    ("hw_donchian_shifted", "windows", f"{C} - {H}.rolling(30).max().shift(1)", "R10"),
    ("hw_roc", "windows", f"{C} / {C}.shift(10) - 1", "R5"),
    ("hw_obv", "windows", f"(np.sign({C}.diff()).fillna(0) * {V}).cumsum()", "R3"),
    ("hw_rolling_vwap", "windows", f"({C} * {V}).rolling(24).sum() / {V}.rolling(24).sum()", "R1"),
    ("hw_rolling_polyfit_slope", "windows", f"{C}.rolling(30).apply(lambda w: np.polyfit(np.arange(len(w)), w, 1)[0], raw=True)", "R5"),
    ("ht_daily_running_high", "time", f"{H}.groupby({DAY}).cummax()", "R1"),
    ("ht_daily_running_vwap", "time", f"({C} * {V}).groupby({DAY}).cumsum() / {V}.groupby({DAY}).cumsum()", "R1"),
    ("ht_daily_first_open", "time", f"{O}.groupby({DAY}).transform('first')", "R1"),
    ("ht_bars_since_day_start", "time", f"{C}.groupby({DAY}).cumcount()", "R11"),
    ("ht_previous_day_close", "time", _series(f"{C}.groupby({DAY}).last().shift(1).reindex({DAY}).to_numpy()"), "R1"),
    ("ht_previous_week_close", "time", _series(f"{C}.groupby({TS}.dt.to_period('W')).last().shift(1).reindex({TS}.dt.to_period('W')).to_numpy()"), "R1"),
    ("ht_resample_shifted", "time", _series(f"{C}.set_axis({TS}).resample('1D').last().shift(1).reindex({TS}, method='ffill').to_numpy()"), "R1"),
    ("ht_ffill_sparse", "time", f"{C}.where(np.arange(len(df)) % 5 == 0).ffill()", "R1"),
    ("ht_four_hour_running", "time", f"{C}.groupby({TS}.dt.floor('4h')).cummax()", "R1"),
    ("hr_first_row", "wholesample", f"{C} - {C}.iloc[0]", "R2"),
    ("hr_expanding_rank", "wholesample", f"{C}.expanding().apply(lambda w: (w <= w[-1]).mean(), raw=True)", "R8"),
    ("hr_expanding_quantile", "wholesample", f"{C} - {C}.expanding().quantile(0.5)", "R2"),
    ("hr_running_hindsight", "wholesample", f"{C} - {C}.expanding().min()", "R2"),
    ("hr_expanding_minmax", "wholesample", f"({C} - {C}.expanding().min()) / ({C}.expanding().max() - {C}.expanding().min() + 1e-12)", "R8"),
    ("hr_scaled_cummax", "wholesample", f"{C} - 0.99 * {C}.cummax()", "R2"),
    ("hr_expanding_block_mean", "wholesample", f"{C}.groupby(df.index // 100).expanding().mean().reset_index(level=0, drop=True)", "R1"),
    ("hn_lfilter_causal", "arrays", _series(f"scipy.signal.lfilter([0.2] * 5, [1], {CL})"), "R1"),
    ("hn_sosfilt_causal", "arrays", _series(f"scipy.signal.sosfilt(scipy.signal.butter(2, 0.1, output='sos'), {CL})"), "R1"),
    ("hn_uniform_filter_causal", "arrays", _series(f"scipy.ndimage.uniform_filter1d({CL}, 9, origin=4, mode='nearest')"), "R1"),
    ("hn_np_diff_prepend", "arrays", _series(f"np.diff({CL}, prepend={CL}[0])"), "R5"),
    ("hn_np_cumsum_forward", "arrays", _series(f"np.cumsum(np.diff({CL}, prepend={CL}[0]))"), "R3"),
    ("hn_np_convolve_valid_causal", "arrays", _series(f"np.convolve({CL}, np.ones(9) / 9, mode='full')[: len(df)]"), "R1"),
    ("hn_np_cumsum_mean", "arrays", _series(f"np.cumsum({CL}) / np.arange(1, len(df) + 1)"), "R1"),
    ("hn_lstsq_rolling", "arrays", f"{C}.rolling(40).apply(lambda w: np.linalg.lstsq(np.c_[np.ones(len(w)), np.arange(len(w))], w, rcond=None)[0][1], raw=True)", "R5"),
    ("hi_ichimoku_senkou_forward", "indicators", f"(({H}.rolling(9).max() + {L}.rolling(9).min()) / 2).shift(26)", "R1"),
    ("hi_pivot_with_delay", "indicators", f"({H}.shift(2) == {H}.rolling(5).max().shift(0)).astype(float)", "R10"),
    ("hi_keltner_position", "indicators", f"{C} - ({C}.ewm(span=20).mean() + 2 * ({H} - {L}).ewm(span=20).mean())", "R3"),
    ("hi_heikin_ashi_close", "indicators", f"({O} + {H} + {L} + {C}) / 4", "R3"),
    ("hi_trend_strength", "indicators", f"{C}.rolling(50).mean().diff(5)", "R5"),
    ("hl_label_unused", "lookalike", f"{C}.rolling(5).mean()", "R1", ("y = df['close'].shift(-1)",)),
    ("hl_label_shifted_back", "lookalike", f"{C}.shift(1).rolling(5).mean()", "R1", ("y = df['close'].pct_change().shift(-1)",)),
    ("hl_iloc_last_visible", "lookalike", f"{C} - {C}.expanding().apply(lambda w: w[-1], raw=True)", "R2"),
    ("hl_hour_rule", "lookalike", f"({TS}.dt.hour.between(8, 16)).astype(float) - 0.5", "R5"),
    ("hl_weekday_rule", "lookalike", f"({TS}.dt.dayofweek < 2).astype(float) - 0.5", "R5"),
    ("hl_future_named_variable", "lookalike", f"{C}.rolling(7).mean() - {C}.rolling(21).mean()", "R5", ("future = 0",)),
]

__all__ = ["HONEST", "LEAKS"]
