"""Calibrate ``monte-neo discover``: how often it names an indicator on noise, and how big an edge it needs to find.

Writes docs/guides/discover-calibration.md. Runs for several minutes: ``--noise 100 --powers 0.05,0.10,0.15,0.20``.
"""

from __future__ import annotations

import argparse
import math
import sys
import time
import warnings
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests" / "traps"))


def wilson(k: int, n: int, z: float = 1.96) -> tuple[float, float]:
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    r = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return max(0.0, (c - r) / d), min(1.0, (c + r) / d)


def _walk(n: int, seed: int) -> pd.DataFrame:
    from monte_neo.backtest import synthetic_ohlcv

    df = synthetic_ohlcv(n, seed=seed)
    df["timestamp"] = pd.date_range("2022-01-03", periods=n, freq="h")
    return df


def _one(args: tuple) -> tuple[bool, float]:
    kind, n, phi, seed, budget, cost = args
    from monte_neo.discover import Config, discover

    warnings.simplefilter("ignore")
    if kind == "noise":
        df = _walk(n, 1000 + seed)
    else:
        from trap_data import planted_momentum_ohlcv

        df = planted_momentum_ohlcv(n, phi=phi, seed=seed)
    r = discover(df, Config(budget=budget, null_runs=19, seed=seed, cost_bps=cost))
    return bool(r["found"]), float(r["search"]["best_sharpe"])


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--noise", type=int, default=100, help="random walks to search")
    p.add_argument("--runs", type=int, default=20, help="data sets per edge strength")
    p.add_argument("--powers", default="0.05,0.10,0.15,0.20", help="AR(1) coefficients of the planted edge")
    p.add_argument("--sizes", default="1000,3000,10000")
    p.add_argument("--budget", type=int, default=300)
    p.add_argument("--jobs", type=int, default=4)
    p.add_argument("--out", default=str(ROOT / "docs" / "guides" / "discover-calibration.md"))
    a = p.parse_args()
    t0 = time.time()
    lines = [
        "# Discover calibration", "",
        f"Generated by `scripts/discover_calibration.py` (budget {a.budget}, 19 shuffled markets per search, costs 0.5 bp per side).", "",
        "## Noise: how often a search names an indicator on a random walk", "",
        "| Bars | Searches | Named | Rate | 95 % interval | Median best Sharpe of the search |", "|---|---|---|---|---|---|",
    ]
    with ProcessPoolExecutor(a.jobs) as pool:
        for n in (1500,):
            res = list(pool.map(_one, [("noise", n, 0.0, s, a.budget, 0.5) for s in range(a.noise)]))
            k = sum(f for f, _ in res)
            lo, hi = wilson(k, len(res))
            lines.append(f"| {n} | {len(res)} | {k} | {k / len(res):.1%} | {lo:.1%} - {hi:.1%} | {float(np.median([b for _, b in res])):.2f} |")
        lines += ["", "The last column is what a plain search would report as its best strategy on the same data.", "",
                  "## Power: how often a planted AR(1) momentum edge is found", "",
                  "| Bars | AR(1) coefficient | Searches | Found | Rate | 95 % interval |", "|---|---|---|---|---|---|"]
        for n in (int(x) for x in a.sizes.split(",")):
            for phi in (float(x) for x in a.powers.split(",")):
                res = list(pool.map(_one, [("edge", n, phi, 7 + s, a.budget, 0.5) for s in range(a.runs)]))
                k = sum(f for f, _ in res)
                lo, hi = wilson(k, len(res))
                lines.append(f"| {n} | {phi:.2f} | {len(res)} | {k} | {k / len(res):.0%} | {lo:.0%} - {hi:.0%} |")
    lines += ["", f"Run time {time.time() - t0:.0f} s. Costs of 5 bp per side remove the planted edge (see the unit tests); a search that names nothing is a result.", ""]
    Path(a.out).write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
